---
# -----------
# dev
# -----------
spring:
  profiles: dev

datasource:
  falcon:
    url: jdbc:mysql://localhost:3306/falcon?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: falcon
    password: falcon
    driverClassName: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    max-active: 10
    max-idle: 2
    min-idle: 0


logging:
  config: classpath:logback-dev.xml